name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Restore NPM cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install NPM packages
        run: npm ci
      - name: Run tests
        run: npm test

  deploy:
    name: Deploy
    if: github.event_name == 'push'
    needs: [test]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://www.indexfondsenvergelijken.nl
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Restore NPM cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install NPM packages
        run: npm ci

      - name: Build the website
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 8a52e15d16e945b8f72ffec4c9c31396
          projectName: indexfondsenvergelijken
          directory: dist
